
public enum TypeTrie {
	NUM_SEQ_CROISSANT("NUM_SEQ_CROISSANT"),
	NUM_SEQ_DECROISSANT("NUM_SEQ_DECROISSANT"),
	AIRE_FORME_CROISSANT("AIRE_FORME_CROISSANT"),
	AIRE_FORME_DECROISSANT("AIRE_FORME_DECROISSANT"),
	TYPE_FORME_1("TYPE_FORME_1"),
	TYPE_FORME_2("TYPE_FORME_2"),
	DISTANCE_MAXIMALE_CROISSANT("DISTANCE_MAXIMALE_CROISSANT"),
	LARGEUR_CROISSANTE("LARGEUR_CROISSANTE"),
	LARGEUR_DECROISSANTE("LARGEUR_DECROISSANTE"),
	HAUTEUR_CROISSANTE("HAUTEUR_CROISSANTE"),
	HAUTEUR_DECROISSANTE("HAUTEUR_DECROISSANTE"),
	ORDRE_ORIGINAL("ORDRE_ORIGINAL");
	
	private final String nomTrie;
	
	private TypeTrie(String nomTrie) {
		this.nomTrie = nomTrie;
	}
	
	@Override
    public String toString() {
        return nomTrie;
    }
}
