
public enum TypeTrie {
	NUM_SEQ_CROISSANT("NUM_SEQ_CROISSANT"),
	NUM_SEQ_DECROISSANT("NUM_SEQ_DECROISSANT"),
	AIRE_FORME_CROISSANT("AIRE_FORME_CROISSANT"),
	AIRE_FORME_DECROISSANT("AIRE_FORME_DECROISSANT"),
	TYPE_FORME_ALPHABETIQUE("TYPE_FORME_ALPHABETIQUE"),
	TYPE_FORME_ALPHABETIQUE_INVERSE("TYPE_FORME_ALPHABETIQUE_INVERSE"),
	DISTANCE_MAXIMALE_CROISSANTE("DISTANCE_MAXIMALE_CROISSANT"),
	LARGEUR_CROISSANTE("LARGEUR_CROISSANTE"),
	LARGEUR_DECROISSANTE("LARGEUR_DECROISSANTE"),
	HAUTEUR_CROISSANTE("HAUTEUR_CROISSANTE"),
	HAUTEUR_DECROISSANTE("HAUTEUR_DÉCROISSANTE"),
	ORDRE_ORIGINALE("ORDRE_ORIGINALE");
	
	private final String nomTrie;
	
	private TypeTrie(String nomTrie) {
		this.nomTrie = nomTrie;
	}
	
	@Override
    public String toString() {
        return nomTrie;
    }
}
